version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3312
      POSTGRES_DB: Cash_hunter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: cash-hunter-app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:3312@db:5432/Cash_hunter
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:


